### ISSUE TITLE
Google Sign-in Not Authorizing

### ISSUE THREAD

**Issue by sh-biswas** [MLH-Fellowship/Student-Planner#8]
The Google Sign-In is not working. I will have to update the server code in order to configure oauth instead of signing in through the HTML file.

**Comment by V2dha** [comment]
Is it not working on the dashboard or in the front page?  There is javascript code in the html file of front page. It is not working because my api and cliend id had some issues. The client id is the content. 
https://github.com/MLH-Fellowship/Student-Planner/blob/22c9f58ace8ed28d043b9800e912fe9b3a291100/views/homepage.html#L10

I asked emily to send me her api key and client id but she didn't so I used mine for just sometime. It should work fine with emily's api key and client id because it was working in the calendar api authorization as well.

@eamspoker can you send the api key and client id?

**Comment by eamspoker** [comment]
It only seems to work on port 8000, not 3000 for localhost because the way the calendar quickstart is set up with my api key. Would there be a way to host it on localhost:8000 instead?

**Comment by eamspoker** [comment]
Actually, it's probable easier for me to just add localhost:3000 on my oauth credentials. Let me see if the google developer console would let me do that!

**Comment by eamspoker** [comment]
I changed it in the console, but it isn't working for me still on localhost. I'll wait a few hours and see if any changes take place.
